version: '3'

services: 
  db:
    container_name: mysql_sakila
    image: mysql:5.7.28
    volumes:
      - "./data:/var/lib/mysql"
      - ./sakiladb:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root