version: '3'

services: 
  db:
    container_name: mysql_sakila
    image: mysql:5.7.28
    volumes:
      - "./data:/var/lib/mysql"
      - ./sakiladb:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root 